image: docker:git
services:
  - docker:dind
variables:
  IMAGE_NAME: $CI_PROJECT_NAME:$CI_COMMIT_SHA
  IMAGE_NAME_LATEST: $CI_PROJECT_NAME:latest
  GIT_SSL_NO_VERIFY: "1"
#  CLUSTER_NAME: service
#  SERVICE_NAME: spi
before_script:
  - env
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - pip install ecs-deploy
  - pip install docker-compose
  - $(aws ecr get-login --no-include-email --region $AWS_REGION)
#  - curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
#  - chmod +x /usr/local/bin/ecs-cli
  - docker-compose --version
  - export REPOSITORY_URL=$ECR_URL/$IMAGE_NAME
  - export REPOSITORY_URL_LATEST=$ECR_URL/$IMAGE_NAME_LATEST
stages:
  - build
#  - deploy

build:
  stage: build
  script:
    - docker-compose build
    - docker tag $REPOSITORY_URL $REPOSITORY_URL_LATEST
    - docker push $REPOSITORY_URL
    - docker push $REPOSITORY_URL_LATEST
  only:
    - master
  tags:
    - docker
#deploy:
#  stage: deploy
#  script:
#    - ecs deploy --region ${AWS_REGION} --tag ${CI_COMMIT_SHA} ${CLUSTER_NAME} ${SERVICE_NAME} --ignore-warnings --timeout 500
#  only:
#    - master
#  tags:
#    - docker
