version: '3'
services:
  # build is your actual build spec
  build:
    image: ${REPOSITORY_URL}
#    env_file: .env
    build:
      context: .
      args:
        - AWS_REGION=${AWS_REGION}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
